export const CURRENT_PROJECT_UPDATE = 'CURRENT_PROJECT_UPDATE';
export const CURRENT_PROJECT_CREATE_STATION = 'CURRENT_PROJECT_CREATE_STATION';
export const CURRENT_PROJECT_RESTART = 'CURRENT_PROJECT_RESTART';
export const CURRENT_PROJECT_ADD_CORDINATE = 'CURRENT_PROJECT_ADD_CORDINATE';
export const CURRENT_PROJECT_DEL_CORDINATE = 'CURRENT_PROJECT_DEL_CORDINATE';
