export const USER_CREATE_PROJECT = 'USER_CREATE_PROJECT';
export const USER_DELETE_PROJECT = 'USER_DELETE_PROJECT';
export const USER_UPDATE_PROJECTS = 'USER_UPDATE_PROJECTS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SET_JWT = 'USER_SET_JWT';
